services:
  web:
    build: .
    working_dir: /code
    command: >
      sh -c "uv run manage.py migrate &&
             uv run manage.py runserver 0.0.0.0:8000"
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - .:/code
      - /code/.venv
      - /frontend
    environment:
      # pycacheを生成しない設定
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env.local
    depends_on:
      - db

  frontend:
    image: node:24-slim
    working_dir: /code
    command: sh -c "npm install && npx vite build --watch"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/code
      - /code/node_modules
      - ./static/dist:/code/dist
      - ./templates:/code/base_templates:ro
      - ./trail_status/templates:/code/trail_status_templates:ro
    env_file:
      - .env.local
    depends_on:
      - web

  db:
    #profiles:
    #  - ignore
    image: postgres:18-alpine
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: